In [2]:
# experiment no.10

In [3]:
#Aim:- simple line regression for salary data(SLR)

In [5]:
# Name:- Komal S. Harale
# roll no:- 22
# subject:-DSS
# date:-23-09-2026

In [6]:
#importing the basic library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
import os

In [9]:
os.getcwd()

'C:\\Users\\Lenovo'

In [10]:
os.chdir("C:\\Users\\Lenovo\\Desktop")

In [11]:
data=pd.read_csv("salary.csv")

In [12]:
data.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [13]:
data.head(15)

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111

In [14]:
data.tail()

    YearsExperience  Salary
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465

In [15]:
data.shape

(35, 2)

In [16]:
data.size

70

In [17]:
data.ndim

2

In [18]:
data.info

<bound method DataFrame.info of     YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465>

In [19]:
data.describe

<bound method NDFrame.describe of     YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465>

In [20]:
data.isnull().sum

<bound method DataFrame.sum of     YearsExperience  Salary
0             False   False
1             False   False
2             False   False
3             False   False
4             False   False
5             False   False
6             False   False
7             False   False
8             False   False
9             False   False
10            False   False
11            False   False
12            False   False
13            False   False
14            False   False
15            False   False
16            False   False
17            False   False
18            False   False
19            False   False
20            False   False
21            False   False
22            False   False
23            False   False
24            False   False
25            False   False
26            False   False
27            False   False
28            False   False
29            False   False
30            False   False
31            False   False
32            False   False
33            False   False
34            False   False>

In [21]:
#Independent and Dependent Variables
#x = data['YearsExperience']
#y = data['Salary']

## independent and dependent variable

In [23]:
X=data.drop('Salary',axis=1)

In [24]:
X.head()

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [25]:
y=data.Salary

In [26]:
y.head()

0    39343
1    46205
2    37731
3    43525
4    39891
Name: Salary, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=0.30)

In [29]:
print(X_train.shape)

(24, 1)

In [30]:
X_test.shape

(11, 1)

## model fitting

In [31]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

In [32]:
#Assigning Coefficient (slope) to m
m = LR.coef_

In [33]:
print("Coefficient :" , m)

Coefficient : [8528.00205699]

In [34]:
#Assigning Y-intercept to a
c = LR.intercept_

In [35]:
print("Intercept :" , c)

Intercept : 30653.80404187284

## y = mx+c

## prediction

In [37]:
y_pred=LR.predict(X_test)

In [38]:
y_pred

array([120197.8256403 ,  88644.21802942,  74146.61453254, 118492.2252289 ,
        98025.02029212,  72441.01412114,  63913.01206415,  43445.80712736,
        64765.81226984, 112522.623789  , 107405.82255481])

In [39]:
y_test

29    121872
20     91738
16     66029
28    122391
22    101302
15     67938
10     63218
2      37731
11     55794
27    112635
25    105582
Name: Salary, dtype: int64

## Evaluation metric

In [40]:
from sklearn import metrics

In [41]:
# Accuracy
Accuracy = LR.score(X_test, y_test)
Accuracy

0.9714499470616078

In [42]:
# MAE
print(metrics.mean_absolute_error(y_test,y_pred))

3807.469971826513

In [43]:
# MSE
print(np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

4685.185783311836

In [44]:
# RMSE
rmse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
print("RMSE:", rmse)

RMSE: 4685.185783311836